name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run pytest
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Check out code (needed for index.html)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Upload the index.html artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload all files in the root directory
          path: '.'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4